//@version=6
strategy(title="Полосы Боллинджера",
		 overlay=true,
		 default_qty_type=strategy.percent_of_equity,
		 default_qty_value=100,
		 initial_capital=100000,
		 slippage=2,
		 commission_type=strategy.commission.percent,
		 commission_value=0.05,
		 risk_free_rate=0,
		 use_bar_magnifier=true)

source = close
length = input.int(30, minval=1)
mult = input.float(3.0, minval=0.001, maxval=50)
direction = input.int(0, title = "Strategy Direction", minval=-1, maxval=1)
strategy.risk.allow_entry_in(direction == 0 ? strategy.direction.all : (direction < 0 ? strategy.direction.short : strategy.direction.long))
basis = ta.sma(source, length)
dev = mult * ta.stdev(source, length)
upper = basis + dev
lower = basis - dev
if (ta.crossover(source, lower))
	strategy.entry("BBandLE", strategy.long, stop=lower, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandLE")
else
	strategy.cancel(id="BBandLE")
if (ta.crossunder(source, upper))
	strategy.entry("BBandSE", strategy.short, stop=upper, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandSE")
else
	strategy.cancel(id="BBandSE")